# Generated by Django 5.0 on 2023-12-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
