# Generated by Django 5.0 on 2023-12-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='chat.chat'),
        ),
    ]
